"""empty message

Revision ID: 7412b5b82718
Revises: 
Create Date: 2024-05-04 12:38:27.542704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7412b5b82718'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('residence', sa.String(length=255), nullable=False),
    sa.Column('grade', sa.String(length=255), nullable=False),
    sa.Column('desired_jobs', sa.PickleType(), nullable=False),
    sa.Column('brief_biography', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
