"""Describe your changes

Revision ID: ec51e4f3b55c
Revises: 7412b5b82718
Create Date: 2024-05-04 17:03:08.710943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec51e4f3b55c'
down_revision = '7412b5b82718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_column('desired_jobs')
        batch_op.drop_column('brief_biography')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brief_biography', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('desired_jobs', sa.BLOB(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
